apiVersion: v1
kind: Service
metadata:
  name: nestjs-gateway-service
spec:
  selector:
    app: nestjs-gateway
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer