apiVersion: v1
kind: Service
metadata:
  name: nestjs-cart-service
spec:
  selector:
    app: nestjs-cart
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer