apiVersion: apps/v1
kind: Deployment
metadata:
  name: nestjs-customer
  labels:
    app: nestjs-customer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nestjs-customer
  template:
    metadata:
      labels:
        app: nestjs-customer
    spec:
      restartPolicy: Always
      containers:
      - name: nestjs-customer
        image: docker.io/nestjs/customer:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
