apiVersion: v1
kind: Service
metadata:
  name: nestjs-customer-service
spec:
  selector:
    app: nestjs-customer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer